# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic_box.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11generic_box.proto\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty2+\n\x11GenericBoxService\x12\x16\n\x06\x44ust3r\x12\x05.Data\x1a\x05.Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_box_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=21
  _globals['_DATA']._serialized_end=41
  _globals['_EMPTY']._serialized_start=43
  _globals['_EMPTY']._serialized_end=50
  _globals['_GENERICBOXSERVICE']._serialized_start=52
  _globals['_GENERICBOXSERVICE']._serialized_end=95
# @@protoc_insertion_point(module_scope)
