# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generic_box_pb2 as generic__box__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in generic_box_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GenericBoxServiceStub(object):
    """
    Service that receives a data file (binary),loads the data (e.x. matlab format) and returns the a new file with processed data
    :param data: The data to process
    :returns: The transformed data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dust3r = channel.unary_unary(
                '/GenericBoxService/Dust3r',
                request_serializer=generic__box__pb2.Data.SerializeToString,
                response_deserializer=generic__box__pb2.Data.FromString,
                _registered_method=True)


class GenericBoxServiceServicer(object):
    """
    Service that receives a data file (binary),loads the data (e.x. matlab format) and returns the a new file with processed data
    :param data: The data to process
    :returns: The transformed data
    """

    def Dust3r(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenericBoxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dust3r': grpc.unary_unary_rpc_method_handler(
                    servicer.Dust3r,
                    request_deserializer=generic__box__pb2.Data.FromString,
                    response_serializer=generic__box__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GenericBoxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GenericBoxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenericBoxService(object):
    """
    Service that receives a data file (binary),loads the data (e.x. matlab format) and returns the a new file with processed data
    :param data: The data to process
    :returns: The transformed data
    """

    @staticmethod
    def Dust3r(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GenericBoxService/Dust3r',
            generic__box__pb2.Data.SerializeToString,
            generic__box__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
